{
  "formatVersion": "1.1",
  "component": {
    "url": "../../srglogin-core/1.0.0-beta.11/srglogin-core-1.0.0-beta.11.module",
    "group": "ch.srg.login",
    "module": "srglogin-core",
    "version": "1.0.0-beta.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "srglogin-core.aar",
          "url": "srglogin-core-android-1.0.0-beta.11.aar",
          "size": 673759,
          "sha512": "bc18df51d5ac71a1a9edf6e9b45b851bccef7d27ac0ec9a0862c5a0a5201a0080e2ece685a29959f77e0656f1484f863400f317e58ba6daf4430052a3fce74b2",
          "sha256": "c3054d1afe5bf31e3100a1509e24472aa756c1d33a787f8a684e12cb57a46c46",
          "sha1": "eb92421bdac522bde8ef11ab41d404b54a8abf9a",
          "md5": "a8bc16f93edaad020d1b944fd11a2b58"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "srglogin-core.aar",
          "url": "srglogin-core-android-1.0.0-beta.11.aar",
          "size": 673759,
          "sha512": "bc18df51d5ac71a1a9edf6e9b45b851bccef7d27ac0ec9a0862c5a0a5201a0080e2ece685a29959f77e0656f1484f863400f317e58ba6daf4430052a3fce74b2",
          "sha256": "c3054d1afe5bf31e3100a1509e24472aa756c1d33a787f8a684e12cb57a46c46",
          "sha1": "eb92421bdac522bde8ef11ab41d404b54a8abf9a",
          "md5": "a8bc16f93edaad020d1b944fd11a2b58"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "srglogin-core-android-1.0.0-beta.11-sources.jar",
          "url": "srglogin-core-android-1.0.0-beta.11-sources.jar",
          "size": 182469,
          "sha512": "021d95b95eacdaeddf0d4de8819b4f40ad86ea31e45e5736ff974aec1a9ecbd9d81db163de774a72f01d4fde573865132981dbb51007b5ab5d6b23341ac88046",
          "sha256": "debe6856e22ee63dbac5120cad58eb2eca7a68e45a15c0d55f3250198b1d036b",
          "sha1": "80d6f70cea10fa2f0015fe7759803e57131fdc72",
          "md5": "4e60cd1d076883f8e59548ba51e32cb1"
        }
      ]
    }
  ]
}
