{
  "formatVersion": "1.1",
  "component": {
    "url": "../../srglogin-core/1.0.0-rc.2/srglogin-core-1.0.0-rc.2.module",
    "group": "ch.srg.login",
    "module": "srglogin-core",
    "version": "1.0.0-rc.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "srglogin-core.aar",
          "url": "srglogin-core-android-1.0.0-rc.2.aar",
          "size": 831897,
          "sha512": "2a4489fa8a154a9bddc1dda3d62edcfa41d51179a762a5c11c3a23070ef6e6c5a3235db85252cddde7bf9abc5387780b4cf096151f692b7b76095268073e815d",
          "sha256": "67d085b79b67ac8afd295bb4d2e177d3dd0cb5f173706770504c11dc1040a8e7",
          "sha1": "efea7583e21a67df9ece9ff56f2f4326aa3116b5",
          "md5": "2d16142fbf1cf376f7af32b6e1220f40"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.kotlincrypto.hash",
          "module": "sha2",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "srglogin-core.aar",
          "url": "srglogin-core-android-1.0.0-rc.2.aar",
          "size": 831897,
          "sha512": "2a4489fa8a154a9bddc1dda3d62edcfa41d51179a762a5c11c3a23070ef6e6c5a3235db85252cddde7bf9abc5387780b4cf096151f692b7b76095268073e815d",
          "sha256": "67d085b79b67ac8afd295bb4d2e177d3dd0cb5f173706770504c11dc1040a8e7",
          "sha1": "efea7583e21a67df9ece9ff56f2f4326aa3116b5",
          "md5": "2d16142fbf1cf376f7af32b6e1220f40"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "srglogin-core-android-1.0.0-rc.2-sources.jar",
          "url": "srglogin-core-android-1.0.0-rc.2-sources.jar",
          "size": 238673,
          "sha512": "e0bebffdd597c764c377b13b01b003867dc4adc30f488dba1c4667eb4262d7b73fa5e8b8bb7769db3b81d6bd886e736e81b93a9e0dedd55120ea64b74488c0bc",
          "sha256": "9a882da5b7f4eb496daeee4561c5b7983ba8682c6a65dbbbf4f1f16eb6371341",
          "sha1": "431c86a91f7c89414375a6afb2c1b716b3112b24",
          "md5": "6758da0f34c2717538963b4b359b67f8"
        }
      ]
    }
  ]
}
